name: kthcloud-ci
"on":
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    kthcloud-pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 14

            - name: Install dependencies
              run: |
                cd Lab3_Image
                npm install
                
            - name: Run tests
              run: |
                cd Lab3_Image
                npx jest --ci
                
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                registry: registry.cloud.cbh.kth.se
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                
            - name: Build and push image
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ${{ secrets.DOCKER_TAG }}
